config/routes.rb
Rails.application.routes.draw do
  resources :picture_tags
  resources :tags
  resources :pictures do
    resources :comments
  end
  resources :comments
  resources :users
  #resources :sessions, only: [:new, :create, :destroy]
  post 'sessions', to:'sessions#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  delete 'sessions', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :picture_tags, :dependent => :destroy
  has_many :tags, through: :picture_tags
end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :picture_tags
  has_many :pictures, through: :picture_tags

  def self.most_popular
    popular = Tag.all.sort do | tag_1, tag_2 |
      if ((tag_1.pictures.length) > (tag_2.pictures.length))
        -1
      elsif ((tag_1.pictures.length) < (tag_2.pictures.length))
        1
      else
        0
      end
    end
    names = popular.map {|x| x.name}
    names[0..2]
  end

  def self.trending
    trend = Tag.all.sort do | tag_1, tag_2 |
      if ((tag_1.pictures.length) > (tag_2.pictures.length))
        -1
      elsif ((tag_1.pictures.length) < (tag_2.pictures.length))
        1
      else
        0
      end
    end
    trend.first.name
  end

end #class

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :comments
  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, uniqueness: true 
  validates :email, confirmation: true
  validates :email_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def redirect_if_not_logged_in
    if !session[:user_id]
      redirect_to login_path
    end
  end

  def current_user
    @user = User.find(session[:user_id])
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
  end

  def edit
    @comment = Comment.find(params[:id])
    redirect_to edit_comment_path(@comment)
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to user_path(current_user)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.picture_id = session[:picture_id]
    @comment.save
    redirect_to @comment.picture
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_path(current_user)
  end

  # def destroy
  #   if params[:id] == current_user
  #       @comment = Comment.find(params[:id])
  #       @comment.destroy
  #       redirect_to user_path(current_user)
  #   else
  #     flash[:error] = "Nice try!  You do not have permission to delete this photo!"
  #     redirect_to user_path(current_user)
  #   end
  # end

private
  def comment_params
    params.require(:comment).permit(:message, :picture_id, :user_id)
  end

end

app/controllers/picture_tags_controller.rb
class PictureTagsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
    session[:picture_id] = @picture.id
  end

  def edit
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user = current_user
    @picture.save
    redirect_to user_path(current_user)
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to user_path(current_user)
  end

  # def destroy
  #   if params[:id] == current_user
  #       @picture = Picture.find(params[:id])
  #       @picture.destroy
  #       redirect_to user_path(current_user)
  #   else
  #     flash[:error] = "Nice try!  You do not have permission to delete this photo!"
  #     redirect_to user_path(current_user)
  #   end
  # end

private
  def picture_params
    params.require(:picture).permit(:image_url, :title, :user_id, comment_ids: [], tag_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #find the user with that Username
    user = User.find_by(username: params[:username])

    #check if password is legit
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Your username and/or password are invalid. Try again."
      redirect_to login_path
    end

  end #create

  def destroy
    session[:user_id] = nil
    #flash[:success] = “Successfully Logged Out!”
    redirect_to login_path
  end

end #class

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def edit
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user
    @tag.save
    redirect_to_user_path(current_user)
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_logged_in, only: [:index]

  def index
    @user = current_user
  end #index


  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)

    if !user.valid?
      flash[:error] = user.errors.full_messages[0]
      redirect_to signup_path
    else #
      session[:user_id] = user.id
      redirect_to user_path(user)
    end
  end #create

  def update
    #byebug
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    #Destroy user Comments & Pictures if deleting Account
    if @user.comments || @user.pictures
      #Destroy picture_tags first!!
        if @user.comments
          @user.comments.each do |comment|
            comment.message.destroy
          end
        end
        if @user.pictures
          @user.pictures.each do |picture|
            picture.destroy
          end
        end
        @user.destroy
    else
        @user.destroy
    end
    redirect_to login_path
  end

private
  def user_params
    params.require(:user).permit(:username,:email,:email_confirmation,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/picture_tags_helper.rb
module PictureTagsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/picturetags_helper.rb
module PicturetagsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>
<%= form_with model: @comment do |form| %>
<div><% form.text_field :picture_id, value: @picture.id %></div>
 <div><% form.text_field :user_id, value: session[:user_id] %></div>
 <div><%=form.text_area :message, value: @comment.message %></div>
 <%= form.submit %>
<%end%>

app/views/comments/index.html.erb
<h1>Comments </h1>
<p>
  <ul>
    <% @comments.each do |comment| %>
      <li><%= comment.message %></li>
      <%= link_to comment.user.username, user_path(comment.user) %>
       <img src= "<%= comment.picture.image_url %>"> <br><br>
    <%end%>
  </ul>
</p>

app/views/comments/new.html.erb
<h3>Add Comment</h3>
  <%= form_with model: Comment.new do |form| %>
  <div><% form.text_field :picture_id, value: @picture.id %></div>
   <div><% form.text_field :user_id, value: session[:user_id] %></div>
   <div><%=form.text_area :message %></div>
   <%= form.submit %>
 <%end%>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/picture_tags/edit.html.erb
<h1>PictureTags#edit</h1>
<p>Find me in app/views/picture_tags/edit.html.erb</p>

app/views/picture_tags/index.html.erb
<h1>PictureTags#index</h1>
<p>Find me in app/views/picture_tags/index.html.erb</p>

app/views/picture_tags/new.html.erb
<h1>PictureTags#new</h1>
<p>Find me in app/views/picture_tags/new.html.erb</p>

app/views/picture_tags/show.html.erb
<h1>PictureTags#show</h1>
<p>Find me in app/views/picture_tags/show.html.erb</p>

app/views/pictures/edit.html.erb
<h1>Pictures#edit</h1>
<p>Find me in app/views/pictures/edit.html.erb</p>

app/views/pictures/index.html.erb
<h1>Pictures</h1>
<% @pictures.each do |picture| %>
  <%= link_to picture_path(picture) do %>
    <img src= "<%= picture.image_url %>" width = "250" height = "250">
  <%end%>
<%end%>

app/views/pictures/new.html.erb
<h1>Upload New Picture</h1>
<%= form_with model: @picture do |form| %>
 <div>
  Picture url: <%= form.text_field :image_url%>
 </div>
 <div>
  Caption: <%= form.text_field :title%>
 </div>
 <div>
  Tag: <%= form.collection_check_boxes(:tag_ids, Tag.all, :id,:name) %>
 </div>
  <%= form.submit %>
<%end%>

app/views/pictures/show.html.erb
<h1><%= @picture.title %></h1>
<img src= "<%= @picture.image_url %>" width = "500" height = "500">

<h4>Tags: </h4>
  <% @picture.tags.each do |tag| %>
      <%= link_to "#" + "#{tag.name}", tag_path(tag) %>
  <% end %>

<h4>Original Poster: </h4>
  <%= link_to @picture.user.username, user_path(@picture.user) %>


<h3>Comments</h3>
<table>
    <% @picture.comments.each do |comment| %>
    <tr>
      <td><%= link_to comment.user.username, user_path(comment.user) %></td>
      <td><%= comment.message %><td>
    </tr>
    <% end %>
</table>


<%= render template: "comments/new.html.erb", :picture => @picture %>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<h1>Tags</h1>
<h3>Trending</h3>
  <li><%= link_to "#"+ "#{Tag.trending}", Tag.find_by(name: Tag.trending) %></li><br>

<h3>Most Popular</h3>
  <% Tag.most_popular.each do |tag| %>
    <li><%= link_to "#"+ "#{tag}", Tag.find_by(name: tag) %></li>
  <%end%><br>


<h3>Recent Tags</h3>
<ul>
  <% @tags.each do |tag| %>
  <li>  <%=link_to "#"+ "#{tag.name}", tag_path(tag) %> </li>
  <%end%>
</ul>

app/views/tags/new.html.erb
<h1>Add New Tag</h1>
<%= form_with model: @tag do |form| %>
 <div>
  Tag name: <%= form.text_field :name %>
 </div>
  <%= form.submit %>
<%end%>

app/views/tags/show.html.erb
<h1><%= "#" + "#{@tag.name}" %></h1>
<h3>Pictures</h3>
<ul>
    <% @tag.pictures.each do |picture| %>
        <%= link_to picture_path(picture) do %>
          <img src= "<%= picture.image_url %>" width = "250" height = "250">
        <% end %>
    <% end %>
</ul>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= form_with model: @user do |form| %>
 <div>
  Username: <%= form.text_field :username%>
 </div>
 <div>
  Email: <%= form.text_field :email%>
 </div>
 <div>
  Confirm email: <%= form.text_field :email_confirmation %>
 </div>
 <div>
  Password: <%= form.password_field :password %>
 </div>
 <div>
  Confirm Password: <%= form.password_field :password_confirmation %>
 </div>
  <%= form.submit  %>
<%end%>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <%= link_to user.username, user_path(user) %><br>
  <%end%>
</ul>

app/views/users/new.html.erb
<h1>Create User Account</h1>

<%= form_with url:'/signup', model:User.new do |form| %>
 <div>
  Username: <%= form.text_field :username%>
 </div>
 <div>
  Email: <%= form.text_field :email%>
 </div>
 <div>
  Confirm email: <%= form.text_field :email_confirmation %>
 </div>
 <div>
  Password: <%= form.password_field :password %>
 </div>
 <div>
  Confirm Password: <%= form.password_field :password_confirmation %>
 </div>
  <%= form.submit  %>
<%end%>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h3>My Pictures</h3>
<table>
<% @user.pictures.each do |picture| %>
  <%= link_to picture_path(picture) do %>
  <tr>
    <td><img src= "<%= picture.image_url %>" width = "500" height = "500"></td>
    <td>        </td>
    <td><%= button_to 'Delete', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <%end%>
<%end%>
</table>
<br> <br>
<h3>My Comments</h3>
<table>
    <% @user.comments.each do |comment| %>
      <tr>
        <td><%= comment.message %></td>
        <td>          </td>
        <td><%= button_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>
<br><br>
<%= button_to "Cancel Account", @user, method: :delete, data:{confirm: "Are You Sure?"} %>